sudo: true

language: bash

os:
- linux

env:
  - BASHVER=
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4
  - BASHVER=5

matrix:
  include:
    - os: osx

services:
  - docker

script:
  - ./libs/bin/bats -Tr tests

branches:
  only:
    - /.*/

notifications:
  email:
    on_success: never
