# https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal

arch:
  - amd64
  - ppc64le
  - s390x
  - arm64

os:
  - linux
  - osx

jobs:
  allow_failures:
    - os: osx

addons:
  apt:
    packages: bats-core
    update: true
  homebrew:
    packages: bats-core
    update: true

script:
  - bats -Tr tests

branches:
  only:
    - /.*/

notifications:
  email:
    on_success: never
